#!/bin/bash

# NOTE: Ubuntu 16.04 not fully supporting python3

export DEBIAN_FRONTEND=noninteractive

# install python setuptools
apt-get update -q
apt-get clean
rm -rf /var/lib/apt/lists/*

cd /app/data
curl https://transfer.sh/yyy8V/data.tar.gz -o data.tar.gz
tar -xvf data.tar.gz